// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $deleteProfile from "./routes/deleteProfile.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $newProfile from "./routes/newProfile.tsx";
import * as $search from "./routes/search.tsx";
import * as $AddProfile from "./islands/AddProfile.tsx";
import * as $DeleteProfile from "./islands/DeleteProfile.tsx";
import * as $LoginProfile from "./islands/LoginProfile.tsx";
import * as $SearchProfile from "./islands/SearchProfile.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/deleteProfile.tsx": $deleteProfile,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/newProfile.tsx": $newProfile,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/AddProfile.tsx": $AddProfile,
    "./islands/DeleteProfile.tsx": $DeleteProfile,
    "./islands/LoginProfile.tsx": $LoginProfile,
    "./islands/SearchProfile.tsx": $SearchProfile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
